// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OliveMorocco.DataAccess;

#nullable disable

namespace OliveMorocco.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925164104_AddInterventionLignes")]
    partial class AddInterventionLignes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.AvoirFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RetourMarchandise")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("AvoirsFournisseurs", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.AvoirFournisseurLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvoirFournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntrantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AvoirFournisseurId");

                    b.HasIndex("IntrantId");

                    b.ToTable("AvoirFournisseurLignes", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.BonCommandeFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("BonsCommande", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.BonCommandeFournisseurLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BonCommandeFournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IntrantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("QuantiteCommandee")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeFournisseurId");

                    b.HasIndex("IntrantId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BonCommandeLignes", null, t =>
                        {
                            t.HasCheckConstraint("CK_BonCommandeLignes_IntrantOrService", "(\"IntrantId\" IS NOT NULL AND \"ServiceId\" IS NULL) OR (\"IntrantId\" IS NULL AND \"ServiceId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.BonReception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BonCommandeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FactureFournisseurId")
                        .HasColumnType("integer");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalTtc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeId");

                    b.HasIndex("FactureFournisseurId");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("BonsReception", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.BonReceptionLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BRId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntrantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("QuantiteRecue")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BRId");

                    b.HasIndex("IntrantId");

                    b.ToTable("BonReceptionLignes", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InterventionId")
                        .HasColumnType("integer");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("MontantTtc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeChargeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("InterventionId");

                    b.HasIndex("TypeChargeId");

                    b.ToTable("Charges", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.FactureFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstPayee")
                        .HasColumnType("boolean");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RemiseGlobale")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalTtc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("FacturesFournisseurs", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.FactureFournisseurLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BonReceptionId")
                        .HasColumnType("integer");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FactureFournisseurId")
                        .HasColumnType("integer");

                    b.Property<int?>("IntrantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BonReceptionId");

                    b.HasIndex("FactureFournisseurId");

                    b.HasIndex("IntrantId");

                    b.HasIndex("ServiceId");

                    b.ToTable("FactureFournisseurLignes", null, t =>
                        {
                            t.HasCheckConstraint("CK_FactureFournisseurLignes_IntrantOrService", "(\"IntrantId\" IS NOT NULL AND \"ServiceId\" IS NULL) OR (\"IntrantId\" IS NULL AND \"ServiceId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.PaiementFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstEncaisse")
                        .HasColumnType("boolean");

                    b.Property<int>("FactureFournisseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FactureFournisseurId");

                    b.ToTable("PaiementsFournisseurs", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaiementsFournisseurs_Mode", "\"Mode\" IN ('Credit','Cheque','Especes','TPE','Virement','Effet')");
                        });
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("PrixAchatHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reference")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.TypeCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("TypesCharges", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Common.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackupDirectory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BackupEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("BackupIntervalHours")
                        .HasColumnType("integer");

                    b.Property<string>("BackupIntervalUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BackupRetentionDays")
                        .HasColumnType("integer");

                    b.Property<bool>("BlocageSiStockInsuffisant")
                        .HasColumnType("boolean");

                    b.Property<int>("DevisValiditeJoursDefaut")
                        .HasColumnType("integer");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumberingFloorsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EnableVirtualKeyboard")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastBackupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SocieteAdresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SocieteICE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SocieteLogoPath")
                        .HasColumnType("text");

                    b.Property<string>("SocieteMentionsLegales")
                        .HasColumnType("text");

                    b.Property<string>("SocieteNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TauxTVAJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UiLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Common.Tiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConditionsPaiement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ICE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tiers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tiers_Type", "\"Type\" IN ('Client','Fournisseur','LesDeux')");
                        });
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal?>("QuantiteEau")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<int>("SecteurId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("SecteurId");

                    b.ToTable("Interventions", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.InterventionLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("InterventionId")
                        .HasColumnType("integer");

                    b.Property<int>("IntrantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.HasIndex("IntrantId");

                    b.HasIndex("InterventionId", "IntrantId")
                        .IsUnique();

                    b.ToTable("InterventionLignes", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Intrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Intrants", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Pressage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FactureFournisseurId")
                        .HasColumnType("integer");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("QuantiteHuile")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("QuantiteOlives")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Rendement")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VarieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("FactureFournisseurId");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("VarieteId");

                    b.ToTable("Pressages", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Recolte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<int>("SecteurId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VarieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("SecteurId");

                    b.HasIndex("VarieteId");

                    b.ToTable("Recoltes", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Secteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("SuperficieHectares")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Secteurs", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.SecteurVariete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("SecteurId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SuperficieHectares")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VarieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VarieteId");

                    b.HasIndex("SecteurId", "VarieteId")
                        .IsUnique();

                    b.ToTable("SecteurVarietes", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Variete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RegionOrigine")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Varietes", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.AvoirClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FactureId")
                        .HasColumnType("integer");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RetourMarchandise")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FactureId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Avoirs", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.AvoirClientLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvoirClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AvoirClientId");

                    b.HasIndex("ProduitId");

                    b.ToTable("AvoirLignes", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.BonCommandeClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DevisId")
                        .HasColumnType("integer");

                    b.Property<int?>("FactureId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DevisId");

                    b.HasIndex("FactureId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("BonsCommandeClient", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.BonCommandeClientLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BonCommandeClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantiteCommandee")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeClientId");

                    b.HasIndex("ProduitId");

                    b.ToTable("BonCommandeClientLignes", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.BonLivraisonClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BonCommandeClientId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DevisId")
                        .HasColumnType("integer");

                    b.Property<int?>("FactureId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeClientId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DevisId");

                    b.HasIndex("FactureId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("BonsLivraison", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.BonLivraisonClientLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BLId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantiteCommandee")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("QuantiteLivree")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BLId");

                    b.HasIndex("ProduitId");

                    b.ToTable("BonLivraisonLignes", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.DevisClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateValidite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RemiseGlobale")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Devis", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.DevisClientLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DevisClientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DevisClientId");

                    b.HasIndex("ProduitId");

                    b.ToTable("DevisLignes", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.FactureClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BonCommandeReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DevisId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstPayee")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RemiseGlobale")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalTtc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DevisId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Factures", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.FactureClientLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BonLivraisonId")
                        .HasColumnType("integer");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FactureClientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BonLivraisonId");

                    b.HasIndex("FactureClientId");

                    b.HasIndex("ProduitId");

                    b.ToTable("FactureLignes", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrigineId")
                        .HasColumnType("integer");

                    b.Property<string>("OrigineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("StockAvant")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("MouvementsStock", null, t =>
                        {
                            t.HasCheckConstraint("CK_MouvementsStock_Type", "\"Type\" IN ('Entree','Sortie','Ajustement')");
                        });
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.PaiementClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstEncaisse")
                        .HasColumnType("boolean");

                    b.Property<int>("FactureClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FactureClientId");

                    b.ToTable("Paiements", null, t =>
                        {
                            t.HasCheckConstraint("CK_Paiements_Mode", "\"Mode\" IN ('Credit','Cheque','Especes','TPE','Virement','Effet')");
                        });
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("CodeBarre")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<decimal>("PrixAchatHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrixVenteHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StockActuel")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("StockMinimum")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VarieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("VarieteId");

                    b.ToTable("Produits", (string)null);
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.AvoirFournisseur", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Common.Tiers", "Fournisseur")
                        .WithMany("AvoirsFournisseur")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.AvoirFournisseurLigne", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Achat.AvoirFournisseur", "AvoirFournisseur")
                        .WithMany("Lignes")
                        .HasForeignKey("AvoirFournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Intrant", "Intrant")
                        .WithMany()
                        .HasForeignKey("IntrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvoirFournisseur");

                    b.Navigation("Intrant");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.BonCommandeFournisseur", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Common.Tiers", "Fournisseur")
                        .WithMany("BonsCommandeFournisseur")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.BonCommandeFournisseurLigne", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Achat.BonCommandeFournisseur", "BonCommandeFournisseur")
                        .WithMany("Lignes")
                        .HasForeignKey("BonCommandeFournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Intrant", "Intrant")
                        .WithMany()
                        .HasForeignKey("IntrantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OliveMorocco.Domain.Entities.Achat.Service", "Service")
                        .WithMany("BonCommandeFournisseurLignes")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BonCommandeFournisseur");

                    b.Navigation("Intrant");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.BonReception", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Achat.BonCommandeFournisseur", "BonCommande")
                        .WithMany("BonsReception")
                        .HasForeignKey("BonCommandeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OliveMorocco.Domain.Entities.Achat.FactureFournisseur", "FactureFournisseur")
                        .WithMany("BonsReception")
                        .HasForeignKey("FactureFournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OliveMorocco.Domain.Entities.Common.Tiers", "Fournisseur")
                        .WithMany("BonsReception")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BonCommande");

                    b.Navigation("FactureFournisseur");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.BonReceptionLigne", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Achat.BonReception", "BonReception")
                        .WithMany("Lignes")
                        .HasForeignKey("BRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Intrant", "Intrant")
                        .WithMany()
                        .HasForeignKey("IntrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BonReception");

                    b.Navigation("Intrant");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.Charge", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Intervention", "Intervention")
                        .WithMany("Charges")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OliveMorocco.Domain.Entities.Achat.TypeCharge", "TypeCharge")
                        .WithMany("Charges")
                        .HasForeignKey("TypeChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("TypeCharge");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.FactureFournisseur", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Common.Tiers", "Fournisseur")
                        .WithMany("FacturesFournisseur")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.FactureFournisseurLigne", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Achat.BonReception", "BonReception")
                        .WithMany("FactureFournisseurLignes")
                        .HasForeignKey("BonReceptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OliveMorocco.Domain.Entities.Achat.FactureFournisseur", "FactureFournisseur")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureFournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Intrant", "Intrant")
                        .WithMany()
                        .HasForeignKey("IntrantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OliveMorocco.Domain.Entities.Achat.Service", "Service")
                        .WithMany("FactureFournisseurLignes")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BonReception");

                    b.Navigation("FactureFournisseur");

                    b.Navigation("Intrant");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.PaiementFournisseur", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Achat.FactureFournisseur", "FactureFournisseur")
                        .WithMany("Paiements")
                        .HasForeignKey("FactureFournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactureFournisseur");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Intervention", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Secteur", "Secteur")
                        .WithMany("Interventions")
                        .HasForeignKey("SecteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Secteur");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.InterventionLigne", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Intervention", "Intervention")
                        .WithMany("Lignes")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Intrant", "Intrant")
                        .WithMany("InterventionLignes")
                        .HasForeignKey("IntrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("Intrant");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Pressage", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Achat.FactureFournisseur", "FactureFournisseur")
                        .WithMany("Pressages")
                        .HasForeignKey("FactureFournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OliveMorocco.Domain.Entities.Common.Tiers", "Fournisseur")
                        .WithMany("Pressages")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Variete", "Variete")
                        .WithMany("Pressages")
                        .HasForeignKey("VarieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FactureFournisseur");

                    b.Navigation("Fournisseur");

                    b.Navigation("Variete");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Recolte", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Secteur", "Secteur")
                        .WithMany("Recoltes")
                        .HasForeignKey("SecteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Variete", "Variete")
                        .WithMany("Recoltes")
                        .HasForeignKey("VarieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Secteur");

                    b.Navigation("Variete");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.SecteurVariete", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Secteur", "Secteur")
                        .WithMany("SecteurVarietes")
                        .HasForeignKey("SecteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Variete", "Variete")
                        .WithMany("SecteurVarietes")
                        .HasForeignKey("VarieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Secteur");

                    b.Navigation("Variete");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.AvoirClient", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Common.Tiers", "Client")
                        .WithMany("AvoirsClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.FactureClient", "Facture")
                        .WithMany("AvoirsClient")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.AvoirClientLigne", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Vente.AvoirClient", "AvoirClient")
                        .WithMany("Lignes")
                        .HasForeignKey("AvoirClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.Produit", "Produit")
                        .WithMany("AvoirClientLignes")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvoirClient");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.BonCommandeClient", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Common.Tiers", "Client")
                        .WithMany("BonsCommandeClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.DevisClient", "Devis")
                        .WithMany("BonsCommandeClient")
                        .HasForeignKey("DevisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.FactureClient", "Facture")
                        .WithMany("BonsCommandeClient")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Devis");

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.BonCommandeClientLigne", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Vente.BonCommandeClient", "BonCommandeClient")
                        .WithMany("Lignes")
                        .HasForeignKey("BonCommandeClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.Produit", "Produit")
                        .WithMany("BonCommandeClientLignes")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BonCommandeClient");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.BonLivraisonClient", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Vente.BonCommandeClient", "BonCommandeClient")
                        .WithMany("BonsLivraisonClient")
                        .HasForeignKey("BonCommandeClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OliveMorocco.Domain.Entities.Common.Tiers", "Client")
                        .WithMany("BonsLivraisonClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.DevisClient", "Devis")
                        .WithMany("BonsLivraisonClient")
                        .HasForeignKey("DevisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.FactureClient", "Facture")
                        .WithMany("BonsLivraisonClient")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BonCommandeClient");

                    b.Navigation("Client");

                    b.Navigation("Devis");

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.BonLivraisonClientLigne", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Vente.BonLivraisonClient", "BonLivraisonClient")
                        .WithMany("Lignes")
                        .HasForeignKey("BLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.Produit", "Produit")
                        .WithMany("BonLivraisonClientLignes")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BonLivraisonClient");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.DevisClient", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Common.Tiers", "Client")
                        .WithMany("DevisClients")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.DevisClientLigne", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Vente.DevisClient", "DevisClient")
                        .WithMany("Lignes")
                        .HasForeignKey("DevisClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.Produit", "Produit")
                        .WithMany("DevisClientLignes")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DevisClient");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.FactureClient", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Common.Tiers", "Client")
                        .WithMany("FacturesClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.DevisClient", "Devis")
                        .WithMany("FacturesClient")
                        .HasForeignKey("DevisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Devis");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.FactureClientLigne", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Vente.BonLivraisonClient", "BonLivraison")
                        .WithMany("FactureClientLignes")
                        .HasForeignKey("BonLivraisonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.FactureClient", "FactureClient")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OliveMorocco.Domain.Entities.Vente.Produit", "Produit")
                        .WithMany("FactureClientLignes")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BonLivraison");

                    b.Navigation("FactureClient");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.MouvementStock", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Vente.Produit", "Produit")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.PaiementClient", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Vente.FactureClient", "FactureClient")
                        .WithMany("Paiements")
                        .HasForeignKey("FactureClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactureClient");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.Produit", b =>
                {
                    b.HasOne("OliveMorocco.Domain.Entities.Operationnel.Variete", "Variete")
                        .WithMany("Produits")
                        .HasForeignKey("VarieteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Variete");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.AvoirFournisseur", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.BonCommandeFournisseur", b =>
                {
                    b.Navigation("BonsReception");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.BonReception", b =>
                {
                    b.Navigation("FactureFournisseurLignes");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.FactureFournisseur", b =>
                {
                    b.Navigation("BonsReception");

                    b.Navigation("Lignes");

                    b.Navigation("Paiements");

                    b.Navigation("Pressages");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.Service", b =>
                {
                    b.Navigation("BonCommandeFournisseurLignes");

                    b.Navigation("FactureFournisseurLignes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Achat.TypeCharge", b =>
                {
                    b.Navigation("Charges");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Common.Tiers", b =>
                {
                    b.Navigation("AvoirsClient");

                    b.Navigation("AvoirsFournisseur");

                    b.Navigation("BonsCommandeClient");

                    b.Navigation("BonsCommandeFournisseur");

                    b.Navigation("BonsLivraisonClient");

                    b.Navigation("BonsReception");

                    b.Navigation("DevisClients");

                    b.Navigation("FacturesClient");

                    b.Navigation("FacturesFournisseur");

                    b.Navigation("Pressages");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Intervention", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Intrant", b =>
                {
                    b.Navigation("InterventionLignes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Secteur", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("Recoltes");

                    b.Navigation("SecteurVarietes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Operationnel.Variete", b =>
                {
                    b.Navigation("Pressages");

                    b.Navigation("Produits");

                    b.Navigation("Recoltes");

                    b.Navigation("SecteurVarietes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.AvoirClient", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.BonCommandeClient", b =>
                {
                    b.Navigation("BonsLivraisonClient");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.BonLivraisonClient", b =>
                {
                    b.Navigation("FactureClientLignes");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.DevisClient", b =>
                {
                    b.Navigation("BonsCommandeClient");

                    b.Navigation("BonsLivraisonClient");

                    b.Navigation("FacturesClient");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.FactureClient", b =>
                {
                    b.Navigation("AvoirsClient");

                    b.Navigation("BonsCommandeClient");

                    b.Navigation("BonsLivraisonClient");

                    b.Navigation("Lignes");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("OliveMorocco.Domain.Entities.Vente.Produit", b =>
                {
                    b.Navigation("AvoirClientLignes");

                    b.Navigation("BonCommandeClientLignes");

                    b.Navigation("BonLivraisonClientLignes");

                    b.Navigation("DevisClientLignes");

                    b.Navigation("FactureClientLignes");

                    b.Navigation("MouvementsStock");
                });
#pragma warning restore 612, 618
        }
    }
}
